"""
Useful constants for Quantum Belief Propagation.

NUM_PARAMS_SINGLE = 3
NUM_PARAMS_DOUBLE = 9
MATRIX_SIZE_SINGLE = 2
MATRIX_SIZE_DOUBLE = 4
"""

NUM_PARAMS_SINGLE = 3
NUM_PARAMS_DOUBLE = 9
MATRIX_SIZE_SINGLE = 2
MATRIX_SIZE_DOUBLE = 4
